### ISSUE TITLE
2.23 GHz Helix STL file

### ISSUE THREAD

**Issue by lucapandolfini** [Digitelektro/BackfireHelix#2]
Hello, really nice design, thank you.
I was wondering how the 2.23GHz helical feed is meant to be installed. I have seen in the STL file that the base of the helix has no screw holes and its diameter is different from that of the holding arm (which on the contrary fits perfectly the 1.7GHz feed). Do you have any experience/suggestion about how to adapt / modify the arm for this feed? Thank you

**Comment by Digitelektro** [comment]
Hi! Thank you!
Hmm, I was more focusing on the L-band version, I will update the design and add the screw holes over this weekend!
Also somebody reported that the feed holder arm should be longer for S-band. While it works with the current feed holder, a longer one could contribute to the SNR a bit. The problem is I cannot print longer feed holder, I reached my printer capabilities.

**Comment by Digitelektro** [comment]
stl file is updated!

**Comment by lucapandolfini** [comment]
Would it be difficult/time consuming to design an arm that fits the original 2.23 GHz feed (with the same diameter)? I am asking this because I already 3d-printed that... :( thanks a lot!

**Comment by Digitelektro** [comment]
[backfire_helix_holder_for_S_band.zip](https://github.com/Digitelektro/BackfireHelix/files/15347912/backfire_helix_holder_for_S_band.zip)
I didn't tested it, I hope size is good. Good luck!

**Comment by lucapandolfini** [comment]
Thanks a lot, awesome!
